Threshold tuning
mlr-org/mlr3pipelines pull request #152
Opened 2019-04-24 11:53 UTC by Coorsaa

Threshold tuning for classification

- pipeOpPredPostProc
- pipeOpTuneThreshold

- [ ] tests

2020-03-30 11:07 UTC, sumny commented on R/Optimizer.R
> +#'   These [`ParamSet`][paradox::ParamSet] are combined using a [`ParamSetCollection`][paradox::ParamSetCollection].
Default: `ParamSet$new()`

2020-03-30 11:10 UTC, sumny commented on R/Optimizer.R
> +#' @format Abstract [`R6Class`].
``[`R6Class`] object inheriting from [`Optimizer`].``

2020-03-30 11:12 UTC, sumny commented on R/Optimizer.R
> +#' Optimizer$new(param_vals = list())
`OptimizerNloptr$new(param_vals = list())`

2020-03-30 11:14 UTC, sumny commented on R/Optimizer.R
> +#'@section Fields:
Fields section probably not needed due to inherited from `Optimizer`

2020-03-30 11:17 UTC, sumny commented on R/Optimizer.R
> +      requireNamespace("nloptr")
is `requireNamespace` really needed?

2020-03-30 11:19 UTC, sumny commented on R/Optimizer.R
> +#' @format Abstract [`R6Class`].
``[`R6Class`] object inheriting from [`Optimizer`].``

2020-03-30 11:20 UTC, sumny commented on R/Optimizer.R
> +#' Optimizer$new(param_vals = list())
`OptimizerGenSA$new(param_vals = list())`

2020-03-30 11:21 UTC, sumny commented on R/Optimizer.R
> +#'@section Fields:
Fields section probably not needed due to inherited from Optimizer

2020-03-30 11:21 UTC, sumny commented on R/Optimizer.R
> +      requireNamespace("GenSA")
is `requireNamespace` really needed?

2020-03-30 11:29 UTC, sumny commented on R/PipeOpPredPostproc.R
> +#'
`#' @usage NULL`

2020-03-30 11:30 UTC, sumny commented on R/PipeOpPredPostproc.R
> +#'   These [`ParamSet`][paradox::ParamSet] are combined using a [`ParamSetCollection`][paradox::ParamSetCollection].
Default: `ParamSet$new()`

2020-03-30 11:32 UTC, sumny commented on R/PipeOpPredPostproc.R
> +#'
`#' @section Fields:`
``#' Fields inherited from [`PipeOp`].``

2020-03-30 11:37 UTC, sumny commented on R/PipeOpPredPostproc.R
> +#' Inputs are of type [`Task`] during train and predict.
``[`Task`][mlr3::Task]``

2020-03-30 11:40 UTC, sumny commented on R/PipeOpTuneThreshold.R
> +#' @format [`R6Class`] object inheriting from [`PipeOpTaskPreproc`]/[`PipeOp`].
`` #' @format [`R6Class`] object inheriting from [`PipeOpPredPostproc`]/[`PipeOp`].``

2020-03-30 11:46 UTC, sumny commented on R/PipeOpPredPostproc.R
> +#' * `PipeOpPredPostproc$new(id, param_set = ParamSet$new())` \cr
``#' PipeOpPredPostproc$new(id = "predpostproc", param_set = ParamSet$new())``

2020-03-30 11:48 UTC, sumny commented on R/PipeOpTuneThreshold.R
> +#'   Identifier of resulting object.
, default `"tunethreshold"`.

2020-03-30 11:48 UTC, sumny commented on R/PipeOpPredPostproc.R
> +#'   Identifier of resulting object.
, default `"predpostproc"`.

2020-03-30 11:49 UTC, sumny commented on R/PipeOpTuneThreshold.R
> +#' * `PipeOpTuneThreshold$new(id, param_vals = list)` \cr
``#' PipeOpTuneThreshold$new(id = "tunethreshold", param_vals = list)``

2020-03-30 11:50 UTC, sumny commented on R/PipeOpPredPostproc.R
> +#' Outputs are `NULL` during train and [`Prediction`] during predict.
``[`Prediction`][mlr3::Prediction]``

2020-03-30 11:51 UTC, sumny commented on R/PipeOpTuneThreshold.R
> +#' Uses the provided optimizer in order to
Info missing

2020-03-30 11:52 UTC, sumny commented on R/PipeOpTuneThreshold.R
> +#' @section Parameters:
``#' The parameters are the parameters inherited from [`PipeOpPredPostproc`], as well as:``

2020-03-30 11:52 UTC, sumny commented on R/PipeOpTuneThreshold.R
> +#'
maybe, add an example

2020-04-03 15:30 UTC, pfistfl commented
This is currently blocked until `bbotk` hits CRAN, as this should use their Optimizers.

2020-08-13 08:14 UTC, pfistfl commented
This seems to fail due to a missing package, not influenced by the PR.

2020-08-28 15:48 UTC, mb706 requested changes
cosmetic changes only, please merge when fixed

2020-08-28 15:48 UTC, mb706 commented on R/PipeOpTuneThreshold.R
> +#' Learner `predict_type`: `"prob"` is required.
should be a link

2020-08-28 15:48 UTC, mb706 commented on R/PipeOpTuneThreshold.R
> +#' Learner `predict_type`: `"prob"` is required.
(learner)

2020-08-28 15:48 UTC, mb706 commented on R/PipeOpTuneThreshold.R
> +#'    Defaults to `msr("classif.ce")`, i.e. misclassification error.
"initialized to " instead of "defaults to"

2020-08-28 15:48 UTC, mb706 commented on R/PipeOpTuneThreshold.R
> +#'    via [`opt`][bbotk::opt]. Defaults to [`OptimizerGenSA`][bbotk::OptimizerGenSA].
"initialized to " instead of "defaults to"

2020-08-28 15:48 UTC, mb706 commented on R/PipeOpTuneThreshold.R
> +          inherits(x, "Optimizer") | x %in% c("gensa", "nloptr", "random_search")
must return a string describing the error instead of `FALSE` in case of fail

2020-08-28 15:48 UTC, mb706 commented on R/PipeOpTuneThreshold.R
> +        ParamUty$new("log_level", default = "warn", tags = "train")
check for character(1) | integerish(1)

2020-08-28 15:48 UTC, mb706 commented on R/PipeOpTuneThreshold.R
> +      if(!all(input[[1]]$feature_types$type == "numeric"))
braces for multiline if
```r
if (...) {

}
```

2020-08-28 15:48 UTC, mb706 commented on R/PipeOpTuneThreshold.R
> +      pred = private$task_to_prediction(input[[1]])
private functions should start with `.`

2020-08-30 15:11 UTC, merged